export const CORRECT_EMAIL_ERROR_TEXT = "ENTER_CORRECT_EMAIL";
export const CORRECT_PHONE_ERROR_TEXT = "INCORRECT_NUMBER_ENTERED";
export const LATIN_ALPHABET_ERROR_TEXT = "USE_LATIN_ALPHABET_CHARACTERS";
export const DEFAULT_ERROR = "AN_ERROR_OCCURRED";
export const REQUIRED_FIELD_ERROR = "FILL_REQUIRED_FIELD";
